### ISSUE TITLE
fasis install

### ISSUE THREAD

**Issue by yulu0724** [ExplainableML/LanguageGuidance_for_DML#2]
Hi,

I followed the requirement.sh. But I still have problems when importing fasis. Do you have any advices or have you met the same issue before? Thanks!

**Comment by Jackmin801** [comment]
Hello! I am not the author, and your issue is a month old, but I was able to get it working by changing the faiss install to use pip instead. Hope it helps anyone else who is stuck here.

**Comment by sid4sal** [comment]
Problem:-
Installing faiss through `-c pytorch` fails
i.e. `conda install faiss-gpu cudatoolkit=10.2 -c pytorch` doesn't work

Solution:-
You can install faiss through `-c conda-forge`
Use this command --> `conda install faiss-gpu cudatoolkit=10.2 -c conda-forge`
Or you can use pip as indicated by [this comment](https://github.com/ExplainableML/LanguageGuidance_for_DML/issues/2#issuecomment-1163252957)
