### ISSUE TITLE
The training script on SOP dataset

### ISSUE THREAD

**Issue by darkpromise98** [ExplainableML/LanguageGuidance_for_DML#3]
Hello~ 

I find the repo lack the runing script of SOP dataset in 'language_guidance_benchmark_runs.sh'. Is it convenient to provide the corresponding script? Thanks a lot!

**Comment by Confusezius** [comment]
As benefits on finegrained datasets are somewhat limited using the standard language guidance setup, we have primarily included sample runs for datasets with a more usable class separation. 
To make it work, simply replace the training dataset in either one of the sample runs for `cub200` or `cars196` with `online_products`, though you do need to account for the specific weighting of the language regularization.
I'll make sure to include some sample runs for SOP in the near future just as a reference :).
